# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r91
    - name: solr
      image: docker.io/bitnami/solr:9.4.0-debian-11-r1
apiVersion: v2
appVersion: 9.4.0
dependencies:
- condition: zookeeper.enabled
  name: zookeeper
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Solr is an extremely powerful, open source enterprise search platform built on Apache Lucene. It is highly reliable and flexible, scalable, and designed to add value very quickly after launch.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/solr/img/solr-stack-220x234.png
keywords:
- solr
- zookeeper
- apache
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: solr
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/solr
version: 8.3.2
