# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: MachineLearning
  licenses: Apache-2.0
  images: |
    - name: git
      image: docker.io/bitnami/git:2.42.1-debian-11-r0
    - name: mxnet
      image: docker.io/bitnami/mxnet:1.9.1-debian-11-r410
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r90
apiVersion: v2
appVersion: 1.9.1
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache MXNet (Incubating) is a flexible and efficient library for deep learning designed to work as a neural network. Bitnami image ships OpenBLAS as math library.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/mxnet/img/mxnet-stack-220x234.png
keywords:
- mxnet
- python
- machine
- learning
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: mxnet
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mxnet
version: 3.5.1
