# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 11.0.2
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: MariaDB Galera is a multi-primary database cluster solution for synchronous replication and high availability.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/mariadb-galera/img/mariadb-galera-stack-220x234.png
keywords:
  - mariadb
  - mysql
  - database
  - sql
  - prometheus
  - galera
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: mariadb-galera
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/mariadb-galera
version: 9.0.1
