# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: harbor-adapter-trivy
      image: docker.io/bitnami/harbor-adapter-trivy:2.8.3-debian-11-r0
    - name: harbor-core
      image: docker.io/bitnami/harbor-core:2.8.3-debian-11-r0
    - name: harbor-exporter
      image: docker.io/bitnami/harbor-exporter:2.8.3-debian-11-r0
    - name: harbor-jobservice
      image: docker.io/bitnami/harbor-jobservice:2.8.3-debian-11-r0
    - name: harbor-notary-server
      image: docker.io/bitnami/harbor-notary-server:2.8.3-debian-11-r6
    - name: harbor-notary-signer
      image: docker.io/bitnami/harbor-notary-signer:2.8.3-debian-11-r6
    - name: harbor-registry
      image: docker.io/bitnami/harbor-registry:2.8.3-debian-11-r8
    - name: harbor-registryctl
      image: docker.io/bitnami/harbor-registryctl:2.8.3-debian-11-r0
    - name: harbor-portal
      image: docker.io/bitnami/harbor-portal:2.8.3-debian-11-r6
    - name: nginx
      image: docker.io/bitnami/nginx:1.25.1-debian-11-r48
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r28
    - name: postgresql
      image: docker.io/bitnami/postgresql:13.11.0-debian-11-r80
apiVersion: v2
appVersion: 2.8.3
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 17.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Harbor is an open source trusted cloud-native registry to store, sign, and scan content. It adds functionalities like security, identity, and management to the open source Docker distribution.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/harbor-core/img/harbor-core-stack-220x234.png
keywords:
- docker
- registry
- vulnerability
- scan
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: harbor
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/harbor
version: 16.7.4
