{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.dataPlane.metrics.enabled .Values.dataPlane.metrics.serviceMonitor.enabled  }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "apisix.data-plane.fullname" . }}
  namespace: {{ default (include "common.names.namespace" .) .Values.dataPlane.metrics.serviceMonitor.namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: apisix
    app.kubernetes.io/component: data-plane
    {{- if .Values.dataPlane.metrics.serviceMonitor.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.dataPlane.metrics.serviceMonitor.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.dataPlane.metrics.serviceMonitor.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.dataPlane.metrics.serviceMonitor.annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ .Values.dataPlane.metrics.serviceMonitor.jobLabel | quote }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/part-of: apisix
      app.kubernetes.io/component: data-plane
      {{- if .Values.dataPlane.metrics.serviceMonitor.selector }}
      {{- include "common.tplvalues.render" (dict "value" .Values.dataPlane.metrics.serviceMonitor.selector "context" $) | nindent 6 }}
      {{- end }}
  endpoints:
    - port: http-metrics
      path: "/apisix/prometheus/metrics"
      {{- if .Values.dataPlane.metrics.serviceMonitor.interval }}
      interval: {{ .Values.dataPlane.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.dataPlane.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.dataPlane.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.dataPlane.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.dataPlane.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.dataPlane.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.dataPlane.metrics.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.dataPlane.metrics.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.dataPlane.metrics.serviceMonitor.relabelings "context" $) | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
    - {{ include "common.names.namespace" . | quote }}
{{- end }}
