{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.tracking.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mlflow.v0.tracking.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: mlflow
    app.kubernetes.io/component: tracking
    {{- if .Values.tracking.service.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.tracking.service.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.tracking.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" .Values.tracking.service.annotations .Values.commonAnnotations "context" .) | fromYaml }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.tracking.service.type }}
  {{- if and .Values.tracking.service.clusterIP (eq .Values.tracking.service.type "ClusterIP") }}
  clusterIP: {{ .Values.tracking.service.clusterIP }}
  {{- end }}
  {{- if .Values.tracking.service.sessionAffinity }}
  sessionAffinity: {{ .Values.tracking.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.tracking.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.tracking.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.tracking.service.type "LoadBalancer") (eq .Values.tracking.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.tracking.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.tracking.service.type "LoadBalancer") (not (empty .Values.tracking.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.tracking.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.tracking.service.type "LoadBalancer") (not (empty .Values.tracking.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.tracking.service.loadBalancerIP }}
  {{- end }}
  ports:
    {{- if .Values.tracking.tls.enabled }}
    - name: https
      port: {{ .Values.tracking.service.ports.https }}
      protocol: TCP
      {{- if and (or (eq .Values.tracking.service.type "NodePort") (eq .Values.tracking.service.type "LoadBalancer")) (not (empty .Values.tracking.service.nodePorts.https)) }}
      nodePort: {{ .Values.tracking.service.nodePorts.https }}
      {{- else if eq .Values.tracking.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
      targetPort: https
    {{- else }}
    - name: http
      port: {{ .Values.tracking.service.ports.http }}
      protocol: TCP
      {{- if and (or (eq .Values.tracking.service.type "NodePort") (eq .Values.tracking.service.type "LoadBalancer")) (not (empty .Values.tracking.service.nodePorts.http)) }}
      nodePort: {{ .Values.tracking.service.nodePorts.http }}
      {{- else if eq .Values.tracking.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
      targetPort: http
    {{- end }}
    {{- if .Values.tracking.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.tracking.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" .Values.tracking.podLabels .Values.commonLabels "context" .) | fromYaml }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: mlflow
    app.kubernetes.io/component: tracking
{{- end }}
