# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Forum
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.3-debian-11-r1
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r91
    - name: phpbb
      image: docker.io/bitnami/phpbb:3.3.11-debian-11-r0
apiVersion: v2
appVersion: 3.3.11
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: phpBB is a popular bulletin board that features robust messaging capabilities such as flat message structure, subforums, topic split/merge/lock, user groups, full-text search, and attachments.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/phpbb/img/phpbb-stack-220x234.png
keywords:
- phpbb
- forum
- http
- php
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: phpbb
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/phpbb
version: 15.1.2
