# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: apisix-dashboard
      image: docker.io/bitnami/apisix-dashboard:3.0.1-debian-11-r139
    - name: apisix-ingress-controller
      image: docker.io/bitnami/apisix-ingress-controller:1.7.1-debian-11-r0
    - name: apisix
      image: docker.io/bitnami/apisix:3.7.0-debian-11-r0
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r91
apiVersion: v2
appVersion: 3.7.0
dependencies:
- name: etcd
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: etcd.enabled
  version: 9.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache APISIX is high-performance, real-time API Gateway. Features load balancing, dynamic upstream, canary release, circuit breaking, authentication, observability, amongst others.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/apisix/img/apisix-stack-220x234.png
keywords:
- apisix
- ingress
- openresty
- controller
- http
- web
- www
- reverse proxy
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: apisix
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/apisix
- https://github.com/bitnami/charts/tree/main/bitnami/apisix-dashboard
- https://github.com/bitnami/charts/tree/main/bitnami/apisix-ingress-controller
version: 2.2.7
