# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  licenses: Apache-2.0
  images: |
    - name: aws-cli
      image: docker.io/bitnami/aws-cli:2.13.30-debian-11-r0
    - name: azure-cli
      image: docker.io/bitnami/azure-cli:2.53.1-debian-11-r0
    - name: google-cloud-sdk
      image: docker.io/bitnami/google-cloud-sdk:0.453.0-debian-11-r0
    - name: influxdb
      image: docker.io/bitnami/influxdb:2.7.4-debian-11-r0
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r90
apiVersion: v2
appVersion: 2.7.4
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: InfluxDB(TM) is an open source time-series database. It is a core component of the TICK (Telegraf, InfluxDB(TM), Chronograf, Kapacitor) stack.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/influxdb/img/influxdb-stack-220x234.png
keywords:
- influxdb
- tick
- database
- timeseries
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: influxdb
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/influxdb
version: 5.10.2
