# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Wiki
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.3-debian-11-r1
    - name: mediawiki
      image: docker.io/bitnami/mediawiki:1.40.1-debian-11-r4
apiVersion: v2
appVersion: 1.40.1
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - mediawiki-database
  version: 14.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: MediaWiki is the free and open source wiki software that powers Wikipedia. Used by thousands of organizations, it is extremely powerful, scalable software and a feature-rich wiki implementation.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/mediawiki/img/mediawiki-stack-220x234.png
keywords:
- mediawiki
- wiki
- http
- web
- application
- php
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: mediawiki
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mediawiki
version: 17.2.3
