{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if not .Values.dataNode.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "milvus.data-node.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: milvus
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  03_data_node_default.yaml: |
    {{- include "common.tplvalues.render" (dict "value" .Values.dataNode.defaultConfig "context" $) | nindent 4 }}
{{- end }}
