# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  licenses: Apache-2.0
  images: |
    - name: opensearch-dashboards
      image: docker.io/bitnami/opensearch-dashboards:2.11.0-debian-11-r1
    - name: opensearch
      image: docker.io/bitnami/opensearch:2.11.0-debian-11-r1
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r91
apiVersion: v2
appVersion: 2.11.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: OpenSearch is a scalable open-source solution for search, analytics, and observability. Features full-text queries, natural language processing, custom dictionaries, amongst others.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/opensearch/img/opensearch-stack-220x234.png
keywords:
- opensearch
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: opensearch
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/opensearch
version: 0.4.2
