{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.rootCoord.enabled .Values.rootCoord.metrics.enabled .Values.rootCoord.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.root-coordinator.fullname" . }}
  namespace: {{ default (include "common.names.namespace" .) .Values.rootCoord.metrics.serviceMonitor.namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: milvus
    app.kubernetes.io/component: root-coordinator
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.rootCoord.metrics.serviceMonitor.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.rootCoord.metrics.serviceMonitor.labels "context" $ ) | nindent 4 }}
    {{- end }}
   {{- if or .Values.commonAnnotations .Values.rootCoord.metrics.serviceMonitor.annotations }}
   annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.rootCoord.metrics.serviceMonitor.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.rootCoord.metrics.serviceMonitor.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.rootCoord.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.rootCoord.metrics.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      {{- if .Values.rootCoord.metrics.serviceMonitor.selector }}
      {{- include "common.tplvalues.render" (dict "value" .Values.rootCoord.metrics.serviceMonitor.selector "context" $) | nindent 6 }}
      {{- end }}
      app.kubernetes.io/part-of: milvus
      app.kubernetes.io/component: root-coordinator
  endpoints:
    - port: http-metrics
      {{- if .Values.rootCoord.metrics.serviceMonitor.interval }}
      interval: {{ .Values.rootCoord.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.rootCoord.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.rootCoord.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.rootCoord.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.rootCoord.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.rootCoord.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- toYaml .Values.rootCoord.metrics.serviceMonitor.metricRelabelings | nindent 6 }}
      {{- end }}
      {{- if .Values.rootCoord.metrics.serviceMonitor.relabelings }}
      relabelings: {{- toYaml .Values.rootCoord.metrics.serviceMonitor.relabelings | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "common.names.namespace" . | quote }}
{{- end }}
