# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: argo-cd
      image: docker.io/bitnami/argo-cd:2.9.2-debian-11-r0
    - name: dex
      image: docker.io/bitnami/dex:2.37.0-debian-11-r98
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r91
    - name: redis
      image: docker.io/bitnami/redis:7.2.3-debian-11-r1
apiVersion: v2
appVersion: 2.9.2
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Argo CD is a continuous delivery tool for Kubernetes based on GitOps.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/argo-cd/img/argo-cd-stack-220x234.png
keywords:
- Continuous delivery
- Continuous deployment
- Devops
- Kubernetes
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: argo-cd
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/argo-cd
version: 5.2.8
