# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] Review based card movements'
on:
  pull_request_target:
    types:
      - review_requested
      - synchronize
# Remove all permissions by default
permissions: {}
concurrency:
  group: card-movement-${{ github.event.number }}
jobs:
  handler:
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
      contents: read
      issues: read
      pull-requests: read
    # This job will ignore:
    # * Events triggered by bitnami-bot (README commits for example).
    # * Events triggered over automated PRs (They are managed in comments.yml workflow).
    # * PRs with 'bitnami' label.
    if: |
      github.actor != 'bitnami-bot' && github.event.pull_request.user.login != 'bitnami-bot' &&
      (!contains(github.event.pull_request.labels.*.name, 'bitnami')) && (!contains(github.event.pull_request.labels.*.name, 'triage'))
    steps:
      - name: Repo checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Load .env file
        uses: xom9ikk/dotenv@de1ff27d319507880e6621e4d47424c677d95f68
        with:
          path: .github/workflows/
      - name: Move into In Progress
        # Move the card only if the actor is not a Bitnami member
        if: ${{ !contains(fromJson(env.BITNAMI_TEAM), github.actor) }}
        uses: peter-evans/create-or-update-project-card@dfa240db6fe287ceb681e45d6728c1af70452c58
        with:
          project-name: Support
          column-name: In progress
          issue-number: ${{ github.event.number }}
